package com.example.servicesforyou.models.enums;

public enum TownsEnum {
    SOFIA, PLOVDIV, VARNA, BURGAS, RUSE, STARA_ZAGORA, PLEVEN, SLIVEN, DOBRICH, SHUMEN, PERNIK, HASKOVO,
    BLAGOEVGRAD, YAMBOL, VELIKO_TARNOVO, PAZARDZIK, VRATSA, GABROVO, KARDZHALI, MONTANA, VIDIN, LOVECH, KUSTENDIL,
    RAZGRAD, SILISTRA, SMOLYAN, TARGOVISHTE

}
